# Generated by Django 3.2.2 on 2021-08-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_log_hole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_completed',
            field=models.DateTimeField(default='2001-01-01 11:11:11'),
        ),
    ]
